---
version: '3.7'
services:
  traefik:
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/acme.json:/acme.json
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/etc/traefik/dynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TRAEFIK_PILOT_DASHBOARD: false
      TZ: "Europe/Paris"

  sqlghost:
    image: mariadb:${MARIADBVERSION}
    restart: unless-stopped
    volumes:
      - ./conf/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
      - /etc/localtime:/etc/localtime:ro
      - datasqlghost:/var/lib/mysql
      - datasqlghostlog:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOT}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}
      TZ: "Europe/Paris"

  ghost:
    image: ghost:${GHOSTVERSION}
    restart: unless-stopped
    volumes:
      - ./conf/config.production.json:/var/lib/ghost/config.production.json:ro
      - /etc/localtime:/etc/localtime:ro
      - dataghost:/var/lib/ghost/content
    depends_on:
      - sqlghost
    environment:
      TZ: "Europe/Paris"

volumes:
  dataghost:
  datasqlghost:
  datasqlghostlog:
