datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    id: 'prometheus'
    access: 'server'
    org_id: 1
    url: 'http://prometheus:9090'
    is_default: true
    version: 1
    editable: true

